package parser;

public enum CODES_LEX {
    TOKEN_TARGET, ERROR_TARGET, TOKEN_DEPENDENCIES, ERROR_DEPENDENCIES, 
    TOKEN_COMMAND, ERROR_COMMAND, TOKEN_COLON, ERROR_COLON,
    TOKEN_ALL, ERROR_ALL, TOKEN_COMMENT, ERROR_COMMENT,
    TOKEN_COMMA, ERROR_COMMA, TOKEN_TAB, ERROR_TAB, TOKEN_VAR, ERROR_VAR,
    TOKEN_SMCOLON, ERROR_SMCOLON
}