frame_11.png : cube_anim.blend
		blender -b cube_anim.blend -o //frame_# -F PNG -x 1 -f 11
		blender -b cube_anim.blend -o //frame_# -F PNG -x 1 -f 11
		blender -b cube_anim.blend -o //frame_# -F PNG -x 1 -f 11
cube_anim.blend : xxxxx
		rm cube_anim.blend ; unzip cube_anim.zip
		rm cube_anim.blend ; unzip cube_anim.zip
xxxxx : 
	blender -o